# Generated by Django 5.1.6 on 2025-03-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=0, max_length=250, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
